# GitHub Sponsors Configuration
# If you want to enable sponsorship, uncomment and configure below
# 如果您想启用赞助，请取消注释并配置以下内容

# GitHub Sponsors
# github: chenzhuyu2004

# Other platforms / 其他平台
# patreon: your_username
# ko_fi: your_username
# liberapay: your_username
# custom: ["https://your-donation-link.com"]
