# Recommended GitHub Labels for ATLAS Project
# GitHub 项目推荐标签
#
# You can create these labels via Settings → Labels in GitHub
# 可以通过 GitHub 的 Settings → Labels 创建这些标签
#
# Command to create labels programmatically:
# gh label create "label-name" --description "Description" --color "color-hex"

## Type Labels / 类型标签
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working / 有问题"

- name: "feature"
  color: "a2eeef"
  description: "New feature or request / 新功能或请求"

- name: "enhancement"
  color: "a2eeef"
  description: "Improvement to existing features / 改进现有功能"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation / 文档改进或新增"

- name: "performance"
  color: "f9d0c4"
  description: "Performance improvements / 性能改进"

- name: "security"
  color: "ee0701"
  description: "Security vulnerability or concern / 安全漏洞或问题"

- name: "refactor"
  color: "fbca04"
  description: "Code refactoring / 代码重构"

- name: "tests"
  color: "1d76db"
  description: "Testing improvements / 测试改进"

## Priority Labels / 优先级标签
- name: "priority: critical"
  color: "b60205"
  description: "Critical priority / 关键优先级"

- name: "priority: high"
  color: "d93f0b"
  description: "High priority / 高优先级"

- name: "priority: medium"
  color: "fbca04"
  description: "Medium priority / 中等优先级"

- name: "priority: low"
  color: "0e8a16"
  description: "Low priority / 低优先级"

## Status Labels / 状态标签
- name: "status: needs-triage"
  color: "ededed"
  description: "Needs to be triaged / 需要分类"

- name: "status: in-progress"
  color: "1d76db"
  description: "Currently being worked on / 正在处理中"

- name: "status: blocked"
  color: "d93f0b"
  description: "Blocked by another issue / 被其他问题阻塞"

- name: "status: needs-reproduction"
  color: "fef2c0"
  description: "Needs steps to reproduce / 需要复现步骤"

- name: "stale"
  color: "ffffff"
  description: "No recent activity / 长时间无活动"

## Component Labels / 组件标签
- name: "component: dockerfile"
  color: "c5def5"
  description: "Dockerfile changes / Dockerfile 更改"

- name: "component: ci-cd"
  color: "c5def5"
  description: "CI/CD workflow changes / CI/CD 工作流更改"

- name: "component: dependencies"
  color: "0366d6"
  description: "Dependency updates / 依赖更新"

- name: "component: scripts"
  color: "c5def5"
  description: "Shell scripts / Shell 脚本"

- name: "component: docs"
  color: "0075ca"
  description: "Documentation / 文档"

## Special Labels / 特殊标签
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers / 适合新手"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed / 需要额外关注"

- name: "question"
  color: "d876e3"
  description: "Further information is requested / 需要更多信息"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue already exists / 此问题已存在"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on / 不会处理"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right / 这似乎不对"

- name: "pinned"
  color: "0e8a16"
  description: "Pinned issue, won't go stale / 固定问题，不会过期"

- name: "breaking"
  color: "d93f0b"
  description: "Breaking change / 破坏性更改"

## Size Labels / 大小标签 (auto-generated by pr-size-labeler)
- name: "size/XS"
  color: "3CBF00"
  description: "Extra small PR / 极小的 PR"

- name: "size/S"
  color: "5BE12C"
  description: "Small PR / 小 PR"

- name: "size/M"
  color: "FBCA04"
  description: "Medium PR / 中等 PR"

- name: "size/L"
  color: "FF9800"
  description: "Large PR / 大 PR"

- name: "size/XL"
  color: "D93F0B"
  description: "Extra large PR / 超大 PR"

## Dependency Labels / 依赖标签 (auto-generated by Dependabot)
- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file / 更新依赖文件的 PR"

- name: "python"
  color: "2b67c6"
  description: "Python dependencies / Python 依赖"

- name: "docker"
  color: "0db7ed"
  description: "Docker dependencies / Docker 依赖"

- name: "github-actions"
  color: "000000"
  description: "GitHub Actions dependencies / GitHub Actions 依赖"
